enum NotificationType {
  newFollow,
  reactMyPost,
  reactMyComment,
  reactMyReply,
  commentMyPost,
  commentOnPostICommented,
  replyMyComment,
  replyOnMyPost,
  replyOnCommentIReplied,
  searchingForMySpecialization,
  followedDoctorPost,
  followedDoctorNewClinicPost,
  followedDoctorNewDegreePost,
  followedDoctorDiscountPost,
  followedDoctorMedicalInfoPost,
}
